import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useGameDataContext } from '../context/gameData';
import NewGameForm from '../components/newGameForm';

import styles from '../styles/Home.module.css';

export default function Home() {
  const [games, setGames] = useGameDataContext();

  const createNewGame = (gameId, gameData) => {
    setGames({
      ...games,
      [gameId]: gameData,
    });
  };

  const gameCards = Object.keys(games).map(gameId => {
    const game = games[gameId];
    const { playerOne, playerTwo } = game.players;
    return (
      <Link key={gameId} href={`/games/${gameId}`}>
        <a className={styles.card}>
          <div className={styles.cardContainer}>
            <div>{playerOne.name}</div>
            <div>vs.</div>
            <div>{playerTwo.name}</div>
          </div>
          <div className={styles.cardContainer}>
            <div>{playerOne.wins}</div>
            <div></div>
            <div>{playerTwo.wins}</div>
          </div>
        </a>
      </Link>
    );
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Rock|Paper|Scissors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Rock | Paper | Scissors</h1>

        <p className={styles.description}>Create and play multiple games of Rock, Paper, Scissors.</p>

        <NewGameForm submit={createNewGame} />

        <h2>Ongoing Games</h2>
        <div className={styles.grid}>{gameCards}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
